### ISSUE TITLE
can not exec command on Sonoma

### ISSUE THREAD

**Issue by runmain** [cleobis/alfred-cal#7]
can not exec cal, debug info as below
```
[15:34:44.022] Logging Started...
[15:34:45.967] Calendar[Script Filter] Queuing argument ''
[15:34:46.983] Calendar[Script Filter] Script with argv '(null)' finished
[15:34:46.992] ERROR: Calendar[Script Filter] Code 1: .
15:34:46 workflow.py:2093 DEBUG    ---------- Calendar (1.6.3) ----------
15:34:46 workflow.py:1483 DEBUG    reading settings from /Users/xxxxxxx/Library/Application Support/Alfred/Workflow Data/zmin.calendar/settings.json
15:34:46 workflow.py:2394 INFO     checking for update ...
15:34:46 background.py:233 DEBUG    [__workflow_update_check] command cached: /Users/xxxxxxx/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/zmin.calendar/__workflow_update_check.argcache
15:34:46 background.py:237 DEBUG    [__workflow_update_check] passing job to background runner: ['/Library/Developer/CommandLineTools/usr/bin/python3', '-m', 'workflow.background', '__workflow_update_check']
.
15:34:46 workflow.py:2093 DEBUG    ---------- Calendar (1.6.3) ----------
15:34:46 background.py:243 DEBUG    [__workflow_update_check] background job started
15:34:46 format.py:92 INFO     Font: Product Sans 14pt
15:34:46 workflow.py:2114 ERROR    Command '['osascript', './textWidth.scpt', 'Product Sans', '14', '    Su        Mo        Tu        We        Th        Fr        Sa    ', '[["", "", "", "1", "2", "3", "4"], ["5", "6", "\\u2605", "8", "9", "10", "11"], ["12", "13", "14", "15", "16", "17", "18"], ["19", "20", "21", "22", "23", "24", "25"], ["26", "27", "28", "29", "30", "", ""]]']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/Users/xxxxxxx/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.E52A6617-D9B1-4852-AECD-C3CC09DD674A/workflow/workflow.py", line 2107, in run
    func(self)
  File "/Users/xxxxxxx/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.E52A6617-D9B1-4852-AECD-C3CC09DD674A/main.py", line 41, in main
    texts = cal.get_weeks_text(year, month, self.first_day)
  File "/Users/xxxxxxx/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.E52A6617-D9B1-4852-AECD-C3CC09DD674A/cal.py", line 31, in get_weeks_text
    texts += format.format(self.get_cal(self.get_weeks(year, month, first_weekday)), texts[-1])
  File "/Users/xxxxxxx/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.E52A6617-D9B1-4852-AECD-C3CC09DD674A/format.py", line 174, in format
    return self.formatApp(weeks, title)
  File "/Users/xxxxxxx/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.E52A6617-D9B1-4852-AECD-C3CC09DD674A/format.py", line 191, in formatApp
    status = subprocess.run(["osascript", "./textWidth.scpt", self.font[0], str(self.font[1]), title, json.dumps(weeks)],
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['osascript', './textWidth.scpt', 'Product Sans', '14', '    Su        Mo        Tu        We        Th        Fr        Sa    ', '[["", "", "", "1", "2", "3", "4"], ["5", "6", "\\u2605", "8", "9", "10", "11"], ["12", "13", "14", "15", "16", "17", "18"], ["19", "20", "21", "22", "23", "24", "25"], ["26", "27", "28", "29", "30", "", ""]]']' returned non-zero exit status 1.
15:34:46 workflow.py:2136 DEBUG    ---------- finished in 0.782s ----------
[15:34:46.997] Calendar[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'Calendar'</title><subtitle>Command '['osascript', './textWidth.scpt', 'Product Sans', '14', '    Su        Mo        Tu        We        Th        Fr        Sa    ', '[["", "", "", "1", "2", "3", "4"], ["5", "6", "\\u2605", "8", "9", "10", "11"], ["12", "13", "14", "15", "16", "17", "18"], ["19", "20", "21", "22", "23", "24", "25"], ["26", "27", "28", "29", "30", "", ""]]']' returned non-zero exit status 1.</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
```

**Comment by cleobis** [comment]
Thank you for sending in the debugging information. 

If you change the Alfred theme to one of the Alfred default themes, does the error still occur?

Do you have the "Product Sans" font installed on your system?

Can you run the following command in the Terminal application and report what it outputs?
`echo "import AppKit; for f in NSFontManager.shared.availableFonts { print(f) }" | swift repl`

Open Alfred and navigate to the Workflows window. Right click on the Calendar workflow and choose "Open in Terminal". Try running the following command and report what it outputs.
`osascript ./textWidth.scpt 'Product Sans' 14 '    Su        Mo        Tu        We        Th        Fr        Sa    ', '[["", "", "", "1", "2", "3", "4"]]'`

**Comment by runmain** [comment]
tks, Its my problem,  it works when i change font name
sonoma default fontname about sans
![image](https://github.com/cleobis/alfred-cal/assets/8604776/b4b697f5-3ebf-4595-8d55-071b6ab546ba)
